version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: yapi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
